// src/components/DataForm.svelte
<script lang="ts">
    // https://docs.astro.build/es/reference/configuration-reference/#experimentalenv
    import { PRIVATE_FORM_URL } from "astro:env/client";

    let nombres = "";
    let email = "";
    let mensaje = "";
    let telefono = "";
    let enviado = false; // Variable para controlar si el formulario fue enviado

    let errors = {
        nombres: "",
        email: "",
        mensaje: "",
        telefono: "",
    };

    const validarFormulario = (): boolean => {
        let esValido = true;

        // Resetear errores
        errors = { nombres: "", email: "", mensaje: "", telefono: "" };

        // Validacipn del email
        if (!email) {
            errors.email = "Email is mandatory";
            esValido = false;
        } else if (
            !/^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]{2,7}$/.test(email)
        ) {
            errors.email = "Email is not valid";
            esValido = false;
        }

        // Validacipn del nombre
        if (!nombres) {
            errors.nombres = "Name is mandatory";
            esValido = false;
        }

        // Validacipn: El telefono no puede estar vacío
        if (!telefono) {
            errors.telefono = "Phone is mandatory";
            esValido = false;
        }

        // Validacipn del mensaje not empty
        if (!mensaje.trim()) {
            // .trim() para asegurarse que no haya espacios en blanco
            errors.mensaje = "Message is mandatory";
            esValido = false;
        }

        // mssg < 10
        if (mensaje.length < 10) {
            errors.mensaje = "The message must be at least 10 characters long.";
            esValido = false;
        }

        return esValido;
    };

    const enviarFormulario = async (e: Event) => {
        e.preventDefault();

        if (validarFormulario()) {
            // Limpiar los campos y marcar como "enviado" antes de hacer la llamada
            const formData = {
                nombres,
                email,
                mensaje,
                telefono,
            };

            // Limpiar los campos antes de enviar el formulario
            nombres = "";
            email = "";
            mensaje = "";
            telefono = "";
            // Cambiar el estado de 'enviado' inmediatamente dessps de enviar
            enviado = true;

            try {
                // Realizar la llamada fetch a la API

                var myHeaders = new Headers();
                myHeaders.append("Content-Type", "application/json");
                var raw = JSON.stringify(formData);
                var requestOptions: RequestInit = {
                    method: "POST",
                    headers: myHeaders,
                    body: raw,
                    redirect: "follow",
                };

                const response = await fetch(PRIVATE_FORM_URL, requestOptions);

                if (response.ok) {
                    const result = await response.text();
                    // console.log(result);
                }
                // else {
                //     console.log(
                //         "Error al enviar el formulario:",
                //         response.statusText,
                //     );
                // }
            } catch (error) {
                console.error("Error en la solicitud:", error);
            }
        }
    };
</script>

<form novalidate on:submit={enviarFormulario}>
    <div class="mb-4">
        <label
            class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
            for="email"
        ></label>
        <input
            type="email"
            id="email"
            bind:value={email}
            class="w-full px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-primary-500 dark:focus:ring-[#8bdefa]"
            required
        />
        {#if errors.email}
            <p role="alert" class="!text-red-500 !text-sm mt-1">
                {errors.email}
            </p>
        {/if}
    </div>

    <div class="mb-4">
        <label
            class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
            for="nombres">Nombre</label
        >
        <input
            type="text"
            id="nombres"
            class="w-full px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-primary-500 dark:focus:ring-[#8bdefa]"
            bind:value={nombres}
            required
        />
        {#if errors.nombres}
            <p role="alert" class="!text-red-500 !text-sm mt-1">
                {errors.nombres}
            </p>
        {/if}
    </div>

    <div class="mb-4">
        <label
            class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
            for="telefono">Telefono</label
        >
        <input
            type="number"
            id="telefono"
            class="w-full px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-primary-500 dark:focus:ring-[#8bdefa]"
            bind:value={telefono}
            required
        />
        {#if errors.telefono}
            <p role="alert" class="!text-red-500 !text-sm mt-1">
                {errors.telefono}
            </p>
        {/if}
    </div>

    <div class="mb-6">
        <label
            class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
            for="mensaje">Mensaje</label
        >
        <textarea
            class="w-full px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-primary-500 dark:focus:ring-[#8bdefa]"
            id="mensaje"
            rows={5}
            bind:value={mensaje}
            required
        ></textarea>
        {#if errors.mensaje}
            <p role="alert" class="!text-red-500 !text-sm mt-1">
                {errors.mensaje}
            </p>
        {/if}
    </div>

    {#if enviado}
        <!-- Mostrar la tarjeta de "enviado" -->
        <div
            class="text-center p-6 text-[#f5f3ff] dark:bg-[#1f263b] rounded-lg"
        >
            <svg
                class="w-12 h-12 mx-auto mb-4 text-[#6f83bd]"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                ></path>
            </svg>
            <h3
                class="text-xl font-semibold text-gray-900 dark:text-white mb-2"
            >
                Formulario Enviado
            </h3>
            <p class="text-gray-600 dark:text-gray-300">
                Gracias por tu mensaje. Hemos recibido tu formulario y nos
                pondremos en contacto pronto.
            </p>
        </div>
    {:else}
        <button
            type="submit"
            class="w-full inline-flex items-center justify-center px-6 py-3 rounded-lg font-medium transition-all duration-300 focus:outline-none bg-gray-900 hover:bg-gray-800 text-white shadow-md hover:shadow-lg cursor-pointer"
            >Enviar</button
        >
    {/if}
</form>

// src/components/DataForm.tsx
// ---
// import { getLangFromUrl, useTranslations } from "../i18n/utils";

// const lang = getLangFromUrl(Astro.url);
// const t = useTranslations(lang);
// ---
import { useForm, type SubmitHandler } from "react-hook-form"
// https://docs.astro.build/es/reference/configuration-reference/#experimentalenv
import { PRIVATE_FORM_URL } from "astro:env/client"
import { getLangFromUrl, useTranslations } from "../i18n/utils";

type FormData = {
    email: string
    nombres: string
    telefono: string
    mensaje: string
}

interface FormProps {
    link: URL;
}

export default function Form({ link }: FormProps) {

    const {
        register,
        handleSubmit,
        watch,
        formState: { errors },
        formState
    } = useForm<FormData>()

    const onSubmit: SubmitHandler<FormData> = async (data, e) => {
        e?.target.reset();

        // Validar datos antes de enviarlos
        // if (!data.user_email || !data.message) {
        //     console.error("Faltan campos obligatorios");
        //     return;
        // }

        var myHeaders = new Headers();
        myHeaders.append("Content-Type", "application/json");
        var raw = JSON.stringify(data);
        var requestOptions: RequestInit = {
            method: "POST",
            headers: myHeaders,
            body: raw,
            redirect: "follow",
        };

        fetch(PRIVATE_FORM_URL,
            requestOptions
        )
            .then((response) => response.text())
            .then((result) => console.log(result))
            .catch((error) => console.log("error", error));

    }

    const lang = getLangFromUrl(link);
    const t = useTranslations(lang);
    // console.log(link);

    return (
        <form noValidate onSubmit={handleSubmit(onSubmit)}>
            <div className="mb-4">
                <label
                    className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
                >{t("Contact.form.email.label")}</label
                >
                <input
                    type="email"
                    id="contact-email"
                    className="w-full px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-primary-500 dark:focus:ring-[#8bdefa]"
                    placeholder={t("Contact.form.email.placeholder")}
                    {...register("email", {
                        required: true, pattern: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/
                    })}
                />
                {errors.email?.type === "required" && (
                    <p role="alert" className="!text-red-500 !text-sm mt-1">{t("Contact.form.error.email")}</p>
                )}
                {errors.email?.type === "pattern" && (
                    <p role="alert" className="!text-red-500 !text-sm mt-1">{t("Contact.form.error.email.pattern")}</p>
                )}

            </div>

            <div className="mb-4">
                <label
                    className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
                >{t("Contact.form.name.label")}</label
                >
                <input
                    type="text"
                    id="name"
                    className="w-full px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-primary-500 dark:focus:ring-[#8bdefa]"
                    placeholder={t("Contact.form.name.placeholder")}
                    {...register("nombres", { required: true })}
                />
                {errors.nombres?.type === "required" && (
                    <p role="alert" className="!text-red-500 !text-sm mt-1">{t("Contact.form.error.name")}</p>
                )}
            </div>

            <div className="mb-4">
                <label
                    className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
                >{t("Contact.form.phone.label")}</label
                >
                <input
                    type="number"
                    id="phone"
                    className="w-full px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-primary-500 dark:focus:ring-[#8bdefa]"
                    placeholder={t(
                        "Contact.form.phone.placeholder",
                    )}
                    {...register("telefono", { required: true })}
                />
                {errors.telefono?.type === "required" && (
                    <p role="alert" className="!text-red-500 !text-sm mt-1">{t("Contact.form.error.phone")}</p>
                )}
            </div>

            <div className="mb-6">
                <label
                    className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
                >{t("Contact.form.message.label")}</label
                >
                <textarea
                    id="message"
                    rows={5}
                    // name="user_message"
                    className="w-full px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-primary-500 dark:focus:ring-[#8bdefa]"
                    placeholder={t(
                        "Contact.form.message.placeholder",
                    )}
                    {...register("mensaje", { required: true, minLength: 10 })}
                ></textarea>
                {errors.mensaje?.type === "required" && (
                    <p role="alert" className="!text-red-500 !text-sm mt-1">{t("Contact.form.error.message")}</p>
                )}
                {errors.mensaje?.type === "minLength" && (
                    <p role="alert" className="!text-red-500 !text-sm mt-1">{t("Contact.form.error.message.required")}</p>
                )}
            </div>

            {formState.isSubmitSuccessful ? <div className="text-center p-6 text-[#f5f3ff] dark:bg-[#1f263b] rounded-lg">
                <svg
                    className="w-12 h-12 mx-auto mb-4 text-[#6f83bd]"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                    ></path>
                </svg>
                <h3
                    className="text-xl font-semibold text-gray-900 dark:text-white mb-2"
                >
                    {t("Contact.form.cardSend")}
                </h3>
                <p className="text-gray-600 dark:text-gray-300">
                    {t("Contact.form.cardSend.details")}
                </p>
            </div> : <button
                type="submit"
                className="w-full inline-flex items-center justify-center px-6 py-3 rounded-lg font-medium transition-all duration-300 focus:outline-none bg-gray-900 hover:bg-gray-800 text-white shadow-md hover:shadow-lg cursor-pointer"
            >
                {t("Contact.form.submitButton")}
            </button>}


        </form>


    )
}
